# If you want to add a new currency, use this template:
#[short_name]
#name = "Long name of the coin"
#[short_name.exchanges]
#bitfinex = "The name used for access on the Bitfinex API. Default: [short_name] in CAPSLOCK"
#coinmarketcap = "The name used for access on the CoinMarketCap API. Default: name in kebab-case"
# This can be expanded into:
#[eth.exchange.coinmarketcap]
#id = "The name used for access on the CoinMarketCap API. Default: [short_name.name] in kebab-case"
#conversion_symbol = "The symbol used for access on the CoinMarketCap API. Default: [short_name] in lowercase"

# Fiat
[usd]
name = "U.S. Dollar"

[eur]
name = "Euro"

[chf]
name = "Swiss Francs"

# Coins
[eth]
name = "Ethereum"

[btc]
name = "Bitcoin"


[iot]
name = "Iota"
[iot.exchanges]
coinmarketcap = "miota"

# Tokens
[qash]
name = "QASH"
[qash.exchanges]
bitfinex = "QSH"

[req]
name = "Request Network"